version: '3.3'
services:
  mongo-database:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${BETTOR_LEAGUE_MONGO_DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${BETTOR_LEAGUE_MONGO_DATABASE_PASSWORD}
    ports:
      - "27017:27017"

  mongo-express:
    build:
      context: ./mongo-express
      dockerfile: Dockerfile
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${BETTOR_LEAGUE_MONGO_DATABASE_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${BETTOR_LEAGUE_MONGO_DATABASE_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo-database
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "8081:8081"
    depends_on:
      - mongo-database